config/routes.rb
Mymetermaid::Application.routes.draw do
  require 'sidekiq/web'

  #root :to => 'dash#index'

  root :to => 'pages#show', :id => 'home'
  #get "/pages/*id" => 'pages#show', :as => :page, :format => false

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  get "/dash" => "dash#index", as: 'dash'

  resources :payment_processors
  resources :parking_spaces, only: [:index, :show]
  #resources :charges # only: [:new, :index,:show, :destroy, :create]
  resources :parking_events do
    member do
      get '/confirmation' => 'parking_events#confirmation'
    end
  end

  #Sidekiq - Worker Queue
  #constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  #constraints constraint do
  authenticate :admin_user do
    mount Sidekiq::Web => '/admin/sidekiq'
  end
  
end

app/models/payment_processor/my_meter_maid.rb
class PaymentProcessor::MyMeterMaid < PaymentProcessor
#This class is for manual adjustments to account balances
  has_many :charges, :as => :chargeable

end

app/models/payment_processor/payment_processor.rb
class PaymentProcessor < ActiveRecord::Base
  attr_accessible :user_id, :name, :type

  belongs_to :user
  serialize :authorization, Hash 

  validates :name, :presence => true
  validates :user_id, :presence => true
  # validates :type, :uniqueness => { :scope => :user_id,
  #   :message => "Can only create one" }

end

app/models/payment_processor/stripe_mmm.rb
class PaymentProcessor::StripeMmm < PaymentProcessor
  has_many :charges, :as => :chargeable
  
  attr_accessor :token
  attr_accessible :token

  def customer_description
    'Card Ending In - ' + authorization[:last4]
  end

  def charge(amount)
    charge = Stripe::Charge.create(
      :customer    => authorization[:stripe_customer_token],
      :amount      => amount,
      :description => 'Parking',
      :currency    => 'usd'
    )
  end
  def set_customer
    customer = Stripe::Customer.create(description: "Parking", card: token)
    self.authorization[:stripe_customer_token] = customer.id
    self.save
  end

  def self.get_customer(token)
    customer = Stripe::Customer.create(description: "Parking", card: token)
  end

  def self.one_time_charge(token, amount)
    customer = get_customer(token)

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => amount,
      :description => 'Parking',
      :currency    => 'usd'
    )
  end

end

app/controllers/payment_processors_controller.rb
class PaymentProcessorsController < ActionController::Base
  before_filter :authenticate_user!
  layout "application"

  def index
    @payment_processors = PaymentProcessor.where(user_id: current_user.id, status: 'Active')
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @payment_processors }
      format.json { render :json => @payment_processors }
    end
  end

  def show
    @payment_processor = PaymentProcessor.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @payment_processor }
      format.json { render :json => @payment_processor }
    end
  end

  def destroy
    @pp = current_user.payment_processors.find(params[:id])
    @pp.status = 'Inactive'
    @pp.save

  end

  def new

  end

  def create
    puts params.to_yaml
    
  end

end

app/views/payment_processors/index.html.erb
<h1>Payment Processors</h1>


<table>
<tr>
<th>Name</th>
<th>Status</th>
<th>Remove</th>
</tr>
<% @payment_processors.each do |pp| %>
<tr>
<td><%=pp.customer_description%></td>
<td><%=pp.status%></td>
<td><%= link_to 'Destroy', payment_processor_path(pp), :confirm => 'Are you sure?', :method => :delete %></td>
</tr>
<% end %>
</table>

app/views/payment_processors/new.html.erb
<form action="" method="POST" id="payment-form">
  <span class="payment-errors"></span>

  <div class="form-row">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" data-stripe="number"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>CVC</span>
      <input type="text" size="4" data-stripe="cvc"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>Expiration (MM/YYYY)</span>
      <input type="text" size="2" data-stripe="exp-month"/>
    </label>
    <span> / </span>
    <input type="text" size="4" data-stripe="exp-year"/>
  </div>

  <div class="form-row">
    <label>
      <input type="checkbox" name="remember" value="remember">Remember Payment Method?<br>
    </label>
  </div>

  <button type="submit">Submit Payment</button>
</form>