config/routes.rb
Mymetermaid::Application.routes.draw do
  require 'sidekiq/web'

  #root :to => 'dash#index'

  root :to => 'pages#show', :id => 'home'
  #get "/pages/*id" => 'pages#show', :as => :page, :format => false

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  get "/dash" => "dash#index", as: 'dash'

  resources :payment_processors
  resources :parking_spaces, only: [:index, :show]
  #resources :charges # only: [:new, :index,:show, :destroy, :create]
  resources :parking_events do
    member do
      get '/confirmation' => 'parking_events#confirmation'
    end
  end

  #Sidekiq - Worker Queue
  #constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  #constraints constraint do
  authenticate :admin_user do
    mount Sidekiq::Web => '/admin/sidekiq'
  end
  
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <% if current_user.customer? %>
      <li><%= link_to 'Dashboard', dash_path() %></li>
      <li><%= link_to 'Park Now!', new_parking_event_path() %></li>
      <li><%= link_to 'Payment Methods', payment_processors_path() %></li>
    <% end %>
    <li>   
    <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
    <li>
    <%= link_to('Logout (' + current_user.email + ')' , destroy_user_session_path, :method=>'delete') %>
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>
    </li>
    <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "My Meter Maid" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "https://js.stripe.com/v2/"%>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/layouts/home.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "My Meter Maid" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>